### ISSUE TITLE
Canada Blood alcohol level is wrong!

### ISSUE THREAD

**Issue by Extarys** [VincentAudibert/CanIDrive#113]
**Describe the bug**
the default blood alcohol level for Canada is wrong.

**To Reproduce**
1. Go in the setup page
2. Select Canada as the Country
3. See it says 0.8g/L

**Expected behavior**
Maximum blood alcohol level in Canada is 80mg, or 0.08g/L

See [Canada Safety Council](https://canadasafetycouncil.org/canada-s-blood-alcohol-laws-among-strictest-western-world/) as one of the sources

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: ProtonAOSP 12.2.0
 - Version 0.2.4

**Comment by VincentAudibert** [comment]
Thanks for spotting the typo !
Fix on version 0.2.7, being pushed currently on Playstore.
