### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [VincentAudibert/CanIDrive#115]
Hi, this issue has a relation with #114.

We found failures similar in the MainActivity: about you lost form data, lost selection, and changed properties

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159189509-5a8d9732-4b7a-4c73-afa9-baff21a726da.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159189507-928876e1-e5ff-44d1-8c3c-bf96dc34bd4a.png" width=20% height=20%>
</figure>

</div> 
 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159189532-0dfd77a2-ec21-4a9a-bd1e-69adcc9e2e04.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159189529-234b06c8-caaf-408d-86b7-dd729b822c04.png" width=20% height=20%>
</figure>

</div> 
 
A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values. This issue is related to the activity's lifecycle (1). When a screen rotation occurs, the activity is destroyed and resumed. Data loss will happen if the developer does not save the variables before the destruction and restore them after creation. To avoid this, the developers have to implement both the logic necessary to save the activity state in the onSaveInstanceState() callback method and the logic to resume its state in the onRestoreInstanceState() callback method.
Another way to avoid data loss problems is to use the view model, designed to store and manage UI-related data in a lifecycle-conscious way (2).

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

1. https://developer.android.com/guide/components/activities/activity-lifecycle 
2. https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by VincentAudibert** [comment]
@davirec thanks for spotting this, I don't have exactly the same behavior but could replay it with my fairphone3.

On analysis, the weight selection & custom alcohol rate were not stored outside the activity, hence the reset on screen rotation (visible with a single one for me).

Fix brought was to store these in the appropriate service as soon as value changes instead of waiting for user validation.
Part of version 0.2.7 being currently pushed on Playstore.

I will close this issue in about a month (or more) if no feedback on it.
