### ISSUE TITLE
Use a preset of drinks or values upon adding a drink

### ISSUE THREAD

**Issue by VincentAudibert** [VincentAudibert/CanIDrive#22]
To speed up drink selection, show : 
- [x] some restricted options for volume, degree, time
- [x] a full custom option
- [x] a ranked history of drinks, or common drinks

**Comment by ojob** [comment]
Hello,
Proposed additions to this ticket: provide with a list of known order-able alcohols, so that volume and degree are preset, before potential tuning by the user, taking advantage of typical quantities in France (and maybe Europe?)

* glass of wine: 12cL,
   - white wine : 12°
   - red wine : 13°
* beer:
    - pint or half-pint (25cL / 45cL),
    - selection of famous beers, to adjust for the degree (from 0 to 13°)
* Cognac or other « digestive » shooter, or Pastis: typically 4cL of aclohol at 40°.

**Comment by VincentAudibert** [comment]
To propose a preset of usual drinks is a good idea as long as the drink is "generic". 👍 
To some extend, this preset could also be localized (cf country selection) ?

As soon as the degree is based on the name of the drink, we need a huge and certainly incomplete database (especially regarding exploding local beer market).

But all displays won't fit on a single sceen, so tabs or another way to hide unnecessary views is needed (integration of tablayout inside navigation component ?)

**Comment by ojob** [comment]
Indeed, a consumptions catalog is something more elaborated → #83 created

**Comment by VincentAudibert** [comment]
Envisioned design is : 
 - click on add a drink button
 - retrieve & display preset & history drink, merged in one list, sorted by counter
 - either : 
     - select a preset (with name, volume & rate) and validate -> will increment counter
     - select a custom option to enter name, volume & rate and validate -> will add another entry in preset list (with counter 1)

**Comment by VincentAudibert** [comment]
As of 0.2.0, selecting an ingested drink goes by a preset drink catalog, that the user can enrich with each new drink (and simplify as presets are removable) => closed
